--------------------------------------------------------
--  File created - Thursday-December-03-2015   
--------------------------------------------------------
DROP TABLE "TANG_YAO_IND_PROJ"."CLIENT" cascade constraints;
DROP TABLE "TANG_YAO_IND_PROJ"."ENTERTAINER" cascade constraints;
DROP TABLE "TANG_YAO_IND_PROJ"."EVENT" cascade constraints;
DROP TABLE "TANG_YAO_IND_PROJ"."FLORIST" cascade constraints;
DROP TABLE "TANG_YAO_IND_PROJ"."LOCATION" cascade constraints;
DROP TABLE "TANG_YAO_IND_PROJ"."MENU" cascade constraints;
DROP TABLE "TANG_YAO_IND_PROJ"."MUSIC" cascade constraints;
DROP TABLE "TANG_YAO_IND_PROJ"."PHOTOGRAPHER" cascade constraints;
DROP TABLE "TANG_YAO_IND_PROJ"."ZIPS" cascade constraints;
DROP SEQUENCE "TANG_YAO_IND_PROJ"."CLIENT_CLIENTID_SEQ";
DROP SEQUENCE "TANG_YAO_IND_PROJ"."ENTERTAINER_ENTERTAINERID_SEQ";
DROP SEQUENCE "TANG_YAO_IND_PROJ"."EVENT_EVENTID_SEQ";
DROP SEQUENCE "TANG_YAO_IND_PROJ"."FLORIST_FLORISTID_SEQ";
DROP SEQUENCE "TANG_YAO_IND_PROJ"."LOCATION_LOCATIONID_SEQ";
DROP SEQUENCE "TANG_YAO_IND_PROJ"."MENU_MENUID_SEQ";
DROP SEQUENCE "TANG_YAO_IND_PROJ"."MUSIC_MUSICID_SEQ";
DROP SEQUENCE "TANG_YAO_IND_PROJ"."PHOTOGRAPHER_PHOTOGRAPHERID_S";
DROP SEQUENCE "TANG_YAO_IND_PROJ"."ZIPS_ZIPID_SEQ";
--------------------------------------------------------
--  DDL for Sequence CLIENT_CLIENTID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."CLIENT_CLIENTID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ENTERTAINER_ENTERTAINERID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."ENTERTAINER_ENTERTAINERID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EVENT_EVENTID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."EVENT_EVENTID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FLORIST_FLORISTID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."FLORIST_FLORISTID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LOCATION_LOCATIONID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."LOCATION_LOCATIONID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MENU_MENUID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."MENU_MENUID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MUSIC_MUSICID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."MUSIC_MUSICID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PHOTOGRAPHER_PHOTOGRAPHERID_S
--------------------------------------------------------

   CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."PHOTOGRAPHER_PHOTOGRAPHERID_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ZIPS_ZIPID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."ZIPS_ZIPID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "TANG_YAO_IND_PROJ"."CLIENT" 
   (	"CLIENTID" NUMBER(15,0), 
	"CLNAME" VARCHAR2(20 BYTE), 
	"CFNAME" VARCHAR2(20 BYTE), 
	"CPHONE" NUMBER(10,0), 
	"CSTREET" VARCHAR2(40 BYTE), 
	"ZIPID" NUMBER(15,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENTERTAINER
--------------------------------------------------------

  CREATE TABLE "TANG_YAO_IND_PROJ"."ENTERTAINER" 
   (	"ENTERTAINERNAME" VARCHAR2(20 BYTE), 
	"ENTERTAINERPHONE" NUMBER(10,0), 
	"ENTERTAINERTYPE" VARCHAR2(20 BYTE), 
	"ENTERTAINERID" NUMBER(15,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVENT
--------------------------------------------------------

  CREATE TABLE "TANG_YAO_IND_PROJ"."EVENT" 
   (	"EVENTID" NUMBER(15,0), 
	"CLIENTID" NUMBER(15,0), 
	"EVENTDATE" DATE, 
	"EVENTSTARTTIME" NUMBER(2,0), 
	"EVENTDURATION" NUMBER(2,0), 
	"EVENTTYPE" VARCHAR2(20 BYTE), 
	"NUMBERGUESTS" NUMBER(10,0), 
	"LOCATIONID" NUMBER(15,0), 
	"LINENCOLORREQUESTED" VARCHAR2(20 BYTE), 
	"NUMBERWAITERS" NUMBER(10,0), 
	"NUMBERBARTENDERS" NUMBER(10,0), 
	"FLORISTID" NUMBER(15,0), 
	"FLORISTCOST" NUMBER(10,2), 
	"MUSICID" NUMBER(15,0), 
	"MUSICCOST" NUMBER(10,2), 
	"PHOTOGRAPHERID" NUMBER(15,0), 
	"PHOTOGRAPHERCOST" NUMBER(10,2), 
	"MENUID" NUMBER(15,0), 
	"ENTERTAINERCOST" NUMBER(10,2), 
	"ENTERTAINERID" NUMBER(15,0), 
	"TOTALPRICE" NUMBER(10,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FLORIST
--------------------------------------------------------

  CREATE TABLE "TANG_YAO_IND_PROJ"."FLORIST" 
   (	"FLORISTNAME" VARCHAR2(40 BYTE), 
	"FLORISTPHONE" NUMBER(10,0), 
	"FLORISTID" NUMBER(15,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE "TANG_YAO_IND_PROJ"."LOCATION" 
   (	"LOCATIONNAME" VARCHAR2(40 BYTE), 
	"LOCATIONSTREET" VARCHAR2(40 BYTE), 
	"ZIPID" NUMBER(15,0), 
	"LOCATIONID" NUMBER(15,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "TANG_YAO_IND_PROJ"."MENU" 
   (	"MENUID" NUMBER(15,0), 
	"MENUAPPETIZER" VARCHAR2(40 BYTE), 
	"MENUSALAD" VARCHAR2(40 BYTE), 
	"MENUMAIN" VARCHAR2(40 BYTE), 
	"MENUDESSERT" VARCHAR2(40 BYTE), 
	"MENUNUMBER" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MUSIC
--------------------------------------------------------

  CREATE TABLE "TANG_YAO_IND_PROJ"."MUSIC" 
   (	"MUSICCONTACT" VARCHAR2(20 BYTE), 
	"MUSICCONTACTPHONE" NUMBER(10,0), 
	"MUSICTYPE" VARCHAR2(20 BYTE), 
	"MUSICID" NUMBER(15,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PHOTOGRAPHER
--------------------------------------------------------

  CREATE TABLE "TANG_YAO_IND_PROJ"."PHOTOGRAPHER" 
   (	"PHOTOGRAPHERNAME" VARCHAR2(20 BYTE), 
	"PHOTOGRAPHERPHONE" NUMBER(10,0), 
	"PHOTOGRAPHERID" NUMBER(15,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZIPS
--------------------------------------------------------

  CREATE TABLE "TANG_YAO_IND_PROJ"."ZIPS" 
   (	"ZIP" NUMBER(5,0), 
	"CITY" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"ZIPID" NUMBER(15,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into TANG_YAO_IND_PROJ.CLIENT 
SET DEFINE OFF;
-- INSERTING into TANG_YAO_IND_PROJ.ENTERTAINER
SET DEFINE OFF;
-- INSERTING into TANG_YAO_IND_PROJ.EVENT
SET DEFINE OFF;
-- INSERTING into TANG_YAO_IND_PROJ.FLORIST
SET DEFINE OFF;
-- INSERTING into TANG_YAO_IND_PROJ.LOCATION
SET DEFINE OFF;
-- INSERTING into TANG_YAO_IND_PROJ.MENU
SET DEFINE OFF;
-- INSERTING into TANG_YAO_IND_PROJ.MUSIC
SET DEFINE OFF;
-- INSERTING into TANG_YAO_IND_PROJ.PHOTOGRAPHER
SET DEFINE OFF;
-- INSERTING into TANG_YAO_IND_PROJ.ZIPS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index LOCATION_UK_LNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."LOCATION_UK_LNAME" ON "TANG_YAO_IND_PROJ"."LOCATION" ("LOCATIONNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT_FK_FLORISTID
--------------------------------------------------------

  CREATE INDEX "TANG_YAO_IND_PROJ"."EVENT_FK_FLORISTID" ON "TANG_YAO_IND_PROJ"."EVENT" ("FLORISTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ZIPS_UK_ZIP
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."ZIPS_UK_ZIP" ON "TANG_YAO_IND_PROJ"."ZIPS" ("ZIP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."EVENT_PK" ON "TANG_YAO_IND_PROJ"."EVENT" ("EVENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MUSIC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."MUSIC_PK" ON "TANG_YAO_IND_PROJ"."MUSIC" ("MUSICID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENTERTAINER_UK2_ENAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."ENTERTAINER_UK2_ENAME" ON "TANG_YAO_IND_PROJ"."ENTERTAINER" ("ENTERTAINERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENTERTAINER_UK1_EPHONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."ENTERTAINER_UK1_EPHONE" ON "TANG_YAO_IND_PROJ"."ENTERTAINER" ("ENTERTAINERPHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MUSIC_UK1_MPHONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."MUSIC_UK1_MPHONE" ON "TANG_YAO_IND_PROJ"."MUSIC" ("MUSICCONTACTPHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT_FK_LOCATIONID
--------------------------------------------------------

  CREATE INDEX "TANG_YAO_IND_PROJ"."EVENT_FK_LOCATIONID" ON "TANG_YAO_IND_PROJ"."EVENT" ("LOCATIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ZIPS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."ZIPS_PK" ON "TANG_YAO_IND_PROJ"."ZIPS" ("ZIPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT_FK_ENTERTAINERID
--------------------------------------------------------

  CREATE INDEX "TANG_YAO_IND_PROJ"."EVENT_FK_ENTERTAINERID" ON "TANG_YAO_IND_PROJ"."EVENT" ("ENTERTAINERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENU_UK1_MNUMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."MENU_UK1_MNUMBER" ON "TANG_YAO_IND_PROJ"."MENU" ("MENUNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT_FK_CLIENTID
--------------------------------------------------------

  CREATE INDEX "TANG_YAO_IND_PROJ"."EVENT_FK_CLIENTID" ON "TANG_YAO_IND_PROJ"."EVENT" ("CLIENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENT_UK1_CFNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."CLIENT_UK1_CFNAME" ON "TANG_YAO_IND_PROJ"."CLIENT" ("CFNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FLORIST_UK1_FPHONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."FLORIST_UK1_FPHONE" ON "TANG_YAO_IND_PROJ"."FLORIST" ("FLORISTPHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOCATION_FK_ZIPID
--------------------------------------------------------

  CREATE INDEX "TANG_YAO_IND_PROJ"."LOCATION_FK_ZIPID" ON "TANG_YAO_IND_PROJ"."LOCATION" ("ZIPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PHOTOGRAPHER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."PHOTOGRAPHER_PK" ON "TANG_YAO_IND_PROJ"."PHOTOGRAPHER" ("PHOTOGRAPHERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT_FK_MENUID
--------------------------------------------------------

  CREATE INDEX "TANG_YAO_IND_PROJ"."EVENT_FK_MENUID" ON "TANG_YAO_IND_PROJ"."EVENT" ("MENUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOCATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."LOCATION_PK" ON "TANG_YAO_IND_PROJ"."LOCATION" ("LOCATIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MUSIC_UK2_MCONTACT
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."MUSIC_UK2_MCONTACT" ON "TANG_YAO_IND_PROJ"."MUSIC" ("MUSICCONTACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FLORIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."FLORIST_PK" ON "TANG_YAO_IND_PROJ"."FLORIST" ("FLORISTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENT_UK2_CLNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."CLIENT_UK2_CLNAME" ON "TANG_YAO_IND_PROJ"."CLIENT" ("CLNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."MENU_PK" ON "TANG_YAO_IND_PROJ"."MENU" ("MENUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PHOTOGRAPHER_UK2_PNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."PHOTOGRAPHER_UK2_PNAME" ON "TANG_YAO_IND_PROJ"."PHOTOGRAPHER" ("PHOTOGRAPHERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT_FK_MUSICID
--------------------------------------------------------

  CREATE INDEX "TANG_YAO_IND_PROJ"."EVENT_FK_MUSICID" ON "TANG_YAO_IND_PROJ"."EVENT" ("MUSICID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENT_FK_ZIPID
--------------------------------------------------------

  CREATE INDEX "TANG_YAO_IND_PROJ"."CLIENT_FK_ZIPID" ON "TANG_YAO_IND_PROJ"."CLIENT" ("ZIPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."CLIENT_PK" ON "TANG_YAO_IND_PROJ"."CLIENT" ("CLIENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PHOTOGRAPHER_UK1_PPHONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."PHOTOGRAPHER_UK1_PPHONE" ON "TANG_YAO_IND_PROJ"."PHOTOGRAPHER" ("PHOTOGRAPHERPHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENTERTAINER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."ENTERTAINER_PK" ON "TANG_YAO_IND_PROJ"."ENTERTAINER" ("ENTERTAINERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENT_FK_PHOTOGRAPHERID
--------------------------------------------------------

  CREATE INDEX "TANG_YAO_IND_PROJ"."EVENT_FK_PHOTOGRAPHERID" ON "TANG_YAO_IND_PROJ"."EVENT" ("PHOTOGRAPHERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FLORIST_UK2_FNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "TANG_YAO_IND_PROJ"."FLORIST_UK2_FNAME" ON "TANG_YAO_IND_PROJ"."FLORIST" ("FLORISTNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PHOTOGRAPHER
--------------------------------------------------------
  ALTER TABLE "TANG_YAO_IND_PROJ"."PHOTOGRAPHER" ADD CONSTRAINT "PHOTOGRAPHER_CHK1_PPHONE" CHECK (REGEXP_LIKE (PHOTOGRAPHERPHONE, '^\d{10}$')) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."PHOTOGRAPHER" ADD CONSTRAINT "PHOTOGRAPHER_PK" PRIMARY KEY ("PHOTOGRAPHERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."PHOTOGRAPHER" MODIFY ("PHOTOGRAPHERPHONE" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."PHOTOGRAPHER" MODIFY ("PHOTOGRAPHERNAME" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."PHOTOGRAPHER" MODIFY ("PHOTOGRAPHERID" NOT NULL ENABLE);
 ALTER TABLE "TANG_YAO_IND_PROJ"."PHOTOGRAPHER" ADD CONSTRAINT "PHOTOGRAPHER_UK1_PPHONE" UNIQUE ("PHOTOGRAPHERPHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
    ALTER TABLE "TANG_YAO_IND_PROJ"."PHOTOGRAPHER" ADD CONSTRAINT "PHOTOGRAPHER_UK1_PNAME" UNIQUE ("PHOTOGRAPHERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENTERTAINER
--------------------------------------------------------
  ALTER TABLE "TANG_YAO_IND_PROJ"."ENTERTAINER" ADD CONSTRAINT "ENTERTAINER_CHK1_EPHONE" CHECK (REGEXP_LIKE (ENTERTAINERPHONE, '^\d{10}$')) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."ENTERTAINER" ADD CONSTRAINT "ENTERTAINER_PK" PRIMARY KEY ("ENTERTAINERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."ENTERTAINER" MODIFY ("ENTERTAINERNAME" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."ENTERTAINER" MODIFY ("ENTERTAINERID" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."ENTERTAINER" MODIFY ("ENTERTAINERPHONE" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."ENTERTAINER" MODIFY ("ENTERTAINERTYPE" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."ENTERTAINER" ADD CONSTRAINT "ENTERTAINER_UK1_ENAME" UNIQUE ("ENTERTAINERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."ENTERTAINER" ADD CONSTRAINT "ENTERTAINER_UK1_EPHONE" UNIQUE ("ENTERTAINERPHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;

--------------------------------------------------------
--  Constraints for Table ZIPS
--------------------------------------------------------
  ALTER TABLE "TANG_YAO_IND_PROJ"."ZIPS" ADD CONSTRAINT "ZIPS_CHK1_ZIP" CHECK (REGEXP_LIKE (ZIP, '^\d{5}$')) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."ZIPS" MODIFY ("ZIP" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."ZIPS" ADD CONSTRAINT "ZIPS_PK" PRIMARY KEY ("ZIPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."ZIPS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."ZIPS" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."ZIPS" MODIFY ("ZIPID" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."ZIPS" ADD CONSTRAINT "ZIPS_UK1_ZIP" UNIQUE ("ZIP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FLORIST
--------------------------------------------------------
  ALTER TABLE "TANG_YAO_IND_PROJ"."FLORIST" ADD CONSTRAINT "FLORIST_CHK1_FPHONE" CHECK (REGEXP_LIKE (FLORISTPHONE, '^\d{10}$')) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."FLORIST" ADD CONSTRAINT "FLORIST_PK" PRIMARY KEY ("FLORISTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."FLORIST" MODIFY ("FLORISTNAME" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."FLORIST" MODIFY ("FLORISTID" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."FLORIST" MODIFY ("FLORISTPHONE" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."FLORIST" ADD CONSTRAINT "FLORIST_UK1_FPHONE" UNIQUE ("FLORISTPHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."FLORIST" ADD CONSTRAINT "FLORIST_UK1_FNAME" UNIQUE ("FLORISTNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MUSIC
--------------------------------------------------------

  ALTER TABLE "TANG_YAO_IND_PROJ"."MUSIC" ADD CONSTRAINT "MUSIC_CHK1_MCPHONE" CHECK (REGEXP_LIKE(MUSICCONTACTPHONE, '^\d{10}$')) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."MUSIC" ADD CONSTRAINT "MUSIC_PK" PRIMARY KEY ("MUSICID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."MUSIC" MODIFY ("MUSICCONTACT" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."MUSIC" MODIFY ("MUSICID" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."MUSIC" MODIFY ("MUSICCONTACTPHONE" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."MUSIC" MODIFY ("MUSICTYPE" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."MUSIC" ADD CONSTRAINT "MUSIC_UK1_MPHONE" UNIQUE ("MUSICCONTACTPHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."MUSIC" ADD CONSTRAINT "MUSIC_UK1_MCONTACT" UNIQUE ("MUSICCONTACT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;

--------------------------------------------------------
--  Constraints for Table EVENT
--------------------------------------------------------
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "ENTERTAINER_CHK11_GNFORHALL" CHECK ((LOCATIONID = 1 and NUMBERGUESTS between 150 and 200) or (LOCATIONID <> 1)) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "ENTERTAINER_CHK10_TPRICE" CHECK (TOTALPRICE >= 0) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "ENTERTAINER_CHK9_ECOST" CHECK (ENTERTAINERCOST >= 0) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "ENTERTAINER_CHK8_PCOST" CHECK (PHOTOGRAPHERCOST >= 0) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "ENTERTAINER_CHK7_MCOST" CHECK (MUSICCOST >= 0) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "ENTERTAINER_CHK6_FCOST" CHECK (FLORISTCOST >= 0) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "ENTERTAINER_CHK5_NBARTENDERS" CHECK (NUMBERBARTENDERS >= 0) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "ENTERTAINER_CHK4_NWAITERS" CHECK (NUMBERWAITERS >= 0) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "ENTERTAINER_CHK3_NGUESTS" CHECK (NUMBERGUESTS >= 0) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "ENTERTAINER_CHK2_EDURATION" CHECK (EVENTDURATION > 0) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "ENTERTAINER_CHK1_ESTIME" CHECK (EVENTSTARTTIME between 0 and 23) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" MODIFY ("EVENTID" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "EVENT_PK" PRIMARY KEY ("EVENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" MODIFY ("CLIENTID" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" MODIFY ("EVENTDATE" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" MODIFY ("EVENTSTARTTIME" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" MODIFY ("EVENTDURATION" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" MODIFY ("EVENTTYPE" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" MODIFY ("NUMBERGUESTS" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" MODIFY ("LOCATIONID" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" MODIFY ("LINENCOLORREQUESTED" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" MODIFY ("NUMBERWAITERS" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" MODIFY ("NUMBERBARTENDERS" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" MODIFY ("TOTALPRICE" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "TANG_YAO_IND_PROJ"."MENU" ADD CONSTRAINT "MENU_CHK1_MNUMBER" CHECK (MENUNUMBER > 0) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."MENU" MODIFY ("MENUID" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."MENU" ADD CONSTRAINT "MENU_PK" PRIMARY KEY ("MENUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."MENU" MODIFY ("MENUAPPETIZER" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."MENU" MODIFY ("MENUSALAD" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."MENU" MODIFY ("MENUMAIN" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."MENU" MODIFY ("MENUDESSERT" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."MENU" MODIFY ("MENUNUMBER" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."MENU" ADD CONSTRAINT "MENU_UK1_MNUMBER" UNIQUE ("MENUNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;

--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "TANG_YAO_IND_PROJ"."LOCATION" ADD CONSTRAINT "LOCATION_PK" PRIMARY KEY ("LOCATIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."LOCATION" MODIFY ("LOCATIONNAME" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."LOCATION" MODIFY ("LOCATIONID" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."LOCATION" MODIFY ("LOCATIONSTREET" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."LOCATION" MODIFY ("ZIPID" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."LOCATION" ADD CONSTRAINT "LOCATION_UK1_LNAME" UNIQUE ("LOCATIONNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "TANG_YAO_IND_PROJ"."CLIENT" ADD CONSTRAINT "CLIENT_CHK1_CPHONE" CHECK (REGEXP_LIKE (CPHONE, '^\d{10}$')) ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."CLIENT" MODIFY ("CLIENTID" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("CLIENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."CLIENT" MODIFY ("CLNAME" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."CLIENT" MODIFY ("CFNAME" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."CLIENT" MODIFY ("CPHONE" NOT NULL ENABLE);
  ALTER TABLE "TANG_YAO_IND_PROJ"."CLIENT" ADD CONSTRAINT "CLIENT_UK1_CLNAME" UNIQUE ("CLNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."CLIENT" ADD CONSTRAINT "CLIENT_UK1_CFNAME" UNIQUE ("CFNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "TANG_YAO_IND_PROJ"."CLIENT" ADD CONSTRAINT "CLIENT_FK1_ZIPID" FOREIGN KEY ("ZIPID")
	  REFERENCES "TANG_YAO_IND_PROJ"."ZIPS" ("ZIPID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "EVENT_FK1_CLIENTID" FOREIGN KEY ("CLIENTID")
	  REFERENCES "TANG_YAO_IND_PROJ"."CLIENT" ("CLIENTID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "EVENT_FK1_ENTERTAINERID" FOREIGN KEY ("ENTERTAINERID")
	  REFERENCES "TANG_YAO_IND_PROJ"."ENTERTAINER" ("ENTERTAINERID") ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "EVENT_FK1_FLORISTID" FOREIGN KEY ("FLORISTID")
	  REFERENCES "TANG_YAO_IND_PROJ"."FLORIST" ("FLORISTID") ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "EVENT_FK1_LOCATIONID" FOREIGN KEY ("LOCATIONID")
	  REFERENCES "TANG_YAO_IND_PROJ"."LOCATION" ("LOCATIONID") ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "EVENT_FK1_MENUID" FOREIGN KEY ("MENUID")
	  REFERENCES "TANG_YAO_IND_PROJ"."MENU" ("MENUID") ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "EVENT_FK1_MUSICID" FOREIGN KEY ("MUSICID")
	  REFERENCES "TANG_YAO_IND_PROJ"."MUSIC" ("MUSICID") ENABLE;
  ALTER TABLE "TANG_YAO_IND_PROJ"."EVENT" ADD CONSTRAINT "EVENT_FK1_PHOTOGRAPHERID" FOREIGN KEY ("PHOTOGRAPHERID")
	  REFERENCES "TANG_YAO_IND_PROJ"."PHOTOGRAPHER" ("PHOTOGRAPHERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "TANG_YAO_IND_PROJ"."LOCATION" ADD CONSTRAINT "LOCATION_FK1_ZIPID" FOREIGN KEY ("ZIPID")
	  REFERENCES "TANG_YAO_IND_PROJ"."ZIPS" ("ZIPID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLIENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TANG_YAO_IND_PROJ"."CLIENT_TRG" 
BEFORE INSERT ON CLIENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CLIENTID IS NULL THEN
      SELECT CLIENT_CLIENTID_SEQ.NEXTVAL INTO :NEW.CLIENTID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TANG_YAO_IND_PROJ"."CLIENT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ENTERTAINER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TANG_YAO_IND_PROJ"."ENTERTAINER_TRG" 
BEFORE INSERT ON ENTERTAINER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ENTERTAINERID IS NULL THEN
      SELECT ENTERTAINER_ENTERTAINERID_SEQ.NEXTVAL INTO :NEW.ENTERTAINERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TANG_YAO_IND_PROJ"."ENTERTAINER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EVENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TANG_YAO_IND_PROJ"."EVENT_TRG" 
BEFORE INSERT ON EVENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.EVENTID IS NULL THEN
      SELECT EVENT_EVENTID_SEQ.NEXTVAL INTO :NEW.EVENTID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TANG_YAO_IND_PROJ"."EVENT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FLORIST_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TANG_YAO_IND_PROJ"."FLORIST_TRG" 
BEFORE INSERT ON FLORIST 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.FLORISTID IS NULL THEN
      SELECT FLORIST_FLORISTID_SEQ.NEXTVAL INTO :NEW.FLORISTID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TANG_YAO_IND_PROJ"."FLORIST_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOCATION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TANG_YAO_IND_PROJ"."LOCATION_TRG" 
BEFORE INSERT ON LOCATION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.LOCATIONID IS NULL THEN
      SELECT LOCATION_LOCATIONID_SEQ.NEXTVAL INTO :NEW.LOCATIONID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TANG_YAO_IND_PROJ"."LOCATION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MENU_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TANG_YAO_IND_PROJ"."MENU_TRG" 
BEFORE INSERT ON MENU 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.MENUID IS NULL THEN
      SELECT MENU_MENUID_SEQ.NEXTVAL INTO :NEW.MENUID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TANG_YAO_IND_PROJ"."MENU_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MUSIC_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TANG_YAO_IND_PROJ"."MUSIC_TRG" 
BEFORE INSERT ON MUSIC 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.MUSICID IS NULL THEN
      SELECT MUSIC_MUSICID_SEQ.NEXTVAL INTO :NEW.MUSICID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TANG_YAO_IND_PROJ"."MUSIC_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PHOTOGRAPHER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TANG_YAO_IND_PROJ"."PHOTOGRAPHER_TRG" 
BEFORE INSERT ON PHOTOGRAPHER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PHOTOGRAPHERID IS NULL THEN
      SELECT PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL INTO :NEW.PHOTOGRAPHERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TANG_YAO_IND_PROJ"."PHOTOGRAPHER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ZIPS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TANG_YAO_IND_PROJ"."ZIPS_TRG" 
BEFORE INSERT ON ZIPS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ZIPID IS NULL THEN
      SELECT ZIPS_ZIPID_SEQ.NEXTVAL INTO :NEW.ZIPID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TANG_YAO_IND_PROJ"."ZIPS_TRG" ENABLE;
-----------------------------------------------------------
-- Trigger For UPDATE including EVENT table
DROP TABLE "TANG_YAO_IND_PROJ"."EVENT_HISTORY" cascade constraints;

DROP TRIGGER "TANG_YAO_IND_PROJ"."EVENT_HIST_TRIG";
/*Create new tables to store history record*/

  CREATE TABLE "TANG_YAO_IND_PROJ"."EVENT_HISTORY" 
   (	"EVENTID" NUMBER(15,0), 
	"CLIENTID" NUMBER(15,0), 
	"EVENTDATE" DATE, 
	"EVENTSTARTTIME" NUMBER(2,0), 
	"EVENTDURATION" NUMBER(2,0), 
	"EVENTTYPE" VARCHAR2(20 BYTE), 
	"NUMBERGUESTS" NUMBER(10,0), 
	"LOCATIONID" NUMBER(15,0), 
	"LINENCOLORREQUESTED" VARCHAR2(20 BYTE), 
	"NUMBERWAITERS" NUMBER(10,0), 
	"NUMBERBARTENDERS" NUMBER(10,0), 
	"FLORISTID" NUMBER(15,0), 
	"FLORISTCOST" NUMBER(10,2), 
	"MUSICID" NUMBER(15,0), 
	"MUSICCOST" NUMBER(10,2), 
	"PHOTOGRAPHERID" NUMBER(15,0), 
	"PHOTOGRAPHERCOST" NUMBER(10,2), 
	"MENUID" NUMBER(15,0), 
	"ENTERTAINERCOST" NUMBER(10,2), 
	"ENTERTAINERID" NUMBER(15,0), 
	"TOTALPRICE" NUMBER(10,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
 
  
/*Create trigger*/

  CREATE OR REPLACE TRIGGER "TANG_YAO_IND_PROJ"."EVENT_HIST_TRIG" 
  BEFORE UPDATE ON EVENT  
  FOR EACH ROW 
  BEGIN
    INSERT INTO EVENT_HISTORY VALUES (:old.EVENTID, :old.CLIENTID, :old.EVENTDATE, :old.EVENTSTARTTIME, :old.EVENTDURATION, 
    :old.EVENTTYPE, :old.NUMBERGUESTS, :old.LOCATIONID, :old.LINENCOLORREQUESTED, :old.NUMBERWAITERS, 
    :old.NUMBERBARTENDERS, :old.FLORISTID, :old.FLORISTCOST, :old.MUSICID, :old.MUSICCOST, :old.PHOTOGRAPHERID, 
    :old.PHOTOGRAPHERCOST, :old.MENUID, :old.ENTERTAINERCOST, :old.ENTERTAINERID, :old.TOTALPRICE);
  END;
/
ALTER TRIGGER "TANG_YAO_IND_PROJ"."EVENT_HIST_TRIG" ENABLE;

  

--In audit trigger, we try to use trigger to store user and date information to track who and when data was created or updated for all 9 tables. With trigger statement, “CREATED_BY CREATED_DATE UPDATE_BY UPDATE_WHEN” are added to all tables record user and date when new data are inserted and updated. 


--------------------------------------------------------
-- Trigger For AUDIT Florist,Location ,menu
--------------------------------------------------------
drop trigger "TANG_YAO_IND_PROJ"."FLORIST_AUDIT_TRIG";
DROP TRIGGER "TANG_YAO_IND_PROJ"."LOCATION_AUDIT_TRIG";
DROP TRIGGER "TANG_YAO_IND_PROJ"."MENU_AUDIT_TRIG";

/*Drop and add four attributes in tables*/

ALTER TABLE FLORIST DROP COLUMN CREATED_BY;
ALTER TABLE FLORIST DROP COLUMN CREATED_DATE;
ALTER TABLE FLORIST DROP COLUMN UPDATED_BY;
ALTER TABLE FLORIST DROP COLUMN UPDATED_DATE;  

ALTER TABLE LOCATION DROP COLUMN CREATED_BY;
ALTER TABLE LOCATION DROP COLUMN CREATED_DATE;
ALTER TABLE LOCATION DROP COLUMN UPDATED_BY;
ALTER TABLE LOCATION DROP COLUMN UPDATED_DATE;  

ALTER TABLE MENU DROP COLUMN CREATED_BY;
ALTER TABLE MENU DROP COLUMN CREATED_DATE;
ALTER TABLE MENU DROP COLUMN UPDATED_BY;
ALTER TABLE MENU DROP COLUMN UPDATED_DATE;  
       
ALTER TABLE FLORIST
  ADD (CREATED_BY VARCHAR2(40 BYTE),
       CREATED_DATE DATE,
       UPDATED_BY VARCHAR2(40 BYTE),
       UPDATED_DATE DATE);
       
ALTER TABLE LOCATION
  ADD (CREATED_BY VARCHAR2(40 BYTE),
       CREATED_DATE DATE,
       UPDATED_BY VARCHAR2(40 BYTE),
       UPDATED_DATE DATE);
       
ALTER TABLE MENU
  ADD (CREATED_BY VARCHAR2(40 BYTE),
       CREATED_DATE DATE,
       UPDATED_BY VARCHAR2(40 BYTE),
       UPDATED_DATE DATE);
       
create or replace TRIGGER "TANG_YAO_IND_PROJ"."FLORIST_AUDIT_TRIG"
  BEFORE INSERT OR UPDATE ON FLORIST
  FOR EACH ROW
BEGIN
	If INSERTING then
		:new.CREATED_BY := user;
		:new.CREATED_DATE := sysdate;
	end if;
	
	if UPDATING then
		:new.UPDATED_BY := user;
		:new.UPDATED_DATE := sysdate;	
	end if;
END;
/ 
ALTER TRIGGER "TANG_YAO_IND_PROJ"."FLORIST_AUDIT_TRIG" ENABLE;
 
create or replace TRIGGER "TANG_YAO_IND_PROJ"."LOCATION_AUDIT_TRIG"
  BEFORE INSERT OR UPDATE ON LOCATION
  FOR EACH ROW
BEGIN
	If INSERTING then
		:new.CREATED_BY := user;
		:new.CREATED_DATE := sysdate;
	end if;
	
	if UPDATING then
		:new.UPDATED_BY := user;
		:new.UPDATED_DATE := sysdate;	
	end if;
END;
/ 
 ALTER TRIGGER "TANG_YAO_IND_PROJ"."LOCATION_AUDIT_TRIG" ENABLE;
 
create or replace TRIGGER "TANG_YAO_IND_PROJ"."MENU_AUDIT_TRIG"
  BEFORE INSERT OR UPDATE ON MENU
  FOR EACH ROW
BEGIN
	If INSERTING then
		:new.CREATED_BY := user;
		:new.CREATED_DATE := sysdate;
	end if;
	
	if UPDATING then
		:new.UPDATED_BY := user;
		:new.UPDATED_DATE := sysdate;	
	end if;
END;
/ 
 ALTER TRIGGER "TANG_YAO_IND_PROJ"."MENU_AUDIT_TRIG" ENABLE;
 


---insert data---
----insert data--zip---
DROP SEQUENCE "TANG_YAO_IND_PROJ"."ZIPS_ZIPID_SEQ" ;
CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."ZIPS_ZIPID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
TRUNCATE TABLE ZIPS;
INSERT INTO zips VALUES ('84067', 'Roy', 'UT ', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('30542', 'Flowery Branch', 'GA', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('60073', 'Round Lake', 'IL ', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('22003', 'Annandale', 'VA ', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('15301', 'Washington', 'PA ', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('27103', 'Winston Salem', 'NC', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('17522', 'Ephrata', 'PA ', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('12130', 'Jamaica Plain', 'MA ', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('15206', 'Pittsburgh', 'PA ', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('14401', 'Bangor', 'ME ', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('28104', 'Matthews', 'NC ', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('17621', 'Bergenfield', 'NJ ', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('97124', 'Hillsboro', 'OR', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('17103', 'Newark', 'NJ ', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('47711', 'Evansville', 'IN ', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('18951', 'Quakertown', 'PA', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('20886', 'Montgomery Village', 'MD', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('16410', 'Cheshire', 'CT', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('57701', 'Rapid City ', 'SD', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('48124', 'Dearborn ', 'MI', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('39208', 'Pearl', 'MS', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('46360', 'Michigan City', 'IN', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('17701', 'Williamsport', 'PA', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('30180', 'Villa Rica', 'GA', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('18944', 'Perkasie', 'PA', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('59404', 'Great Falls', 'MT', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('48706', 'Bay City', 'MI', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('22901', 'Charlottesville', 'VA', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('60172', 'Roselle', 'IL', ZIPS_ZIPID_SEQ.NEXTVAL);
INSERT INTO zips VALUES ('44060', 'Mentor', 'OH', ZIPS_ZIPID_SEQ.NEXTVAL);
---insert data---entertainer---
----drop sequence&create  sequence---
drop sequence  "TANG_YAO_IND_PROJ"."ENTERTAINER_ENTERTAINERID_SEQ" ;
CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."ENTERTAINER_ENTERTAINERID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
----truncate data permenately ------
truncate table ENTERTAINER ;
DROP SEQUENCE"TANG_YAO_IND_PROJ"."ENTERTAINER_ENTERTAINERID_SEQ";
CREATE SEQUENCE"TANG_YAO_IND_PROJ"."ENTERTAINER_ENTERTAINERID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
TRUNCATE TABLE ENTERTAINER; 

 INSERT INTO ENTERTAINER(ENTERTAINERNAME,ENTERTAINERPHONE,ENTERTAINERTYPE,ENTERTAINERID)
 VALUES('Eduardo Arnold',8559475260,'jazz',ENTERTAINER_ENTERTAINERID_SEQ.nextval);
 
 INSERT INTO ENTERTAINER(ENTERTAINERNAME,ENTERTAINERPHONE,ENTERTAINERTYPE,ENTERTAINERID)
 VALUES('Bert Jefferson',8222808378,'flamenco',ENTERTAINER_ENTERTAINERID_SEQ.nextval);
 
 INSERT INTO ENTERTAINER(ENTERTAINERNAME,ENTERTAINERPHONE,ENTERTAINERTYPE,ENTERTAINERID)
 VALUES('Aubrey Marsh',8229111667,'solo dance',ENTERTAINER_ENTERTAINERID_SEQ.nextval);
 
 INSERT INTO ENTERTAINER(ENTERTAINERNAME,ENTERTAINERPHONE,ENTERTAINERTYPE,ENTERTAINERID)
 VALUES('Dan Dean',8999858990,'piano',ENTERTAINER_ENTERTAINERID_SEQ.nextval);
 
 INSERT INTO ENTERTAINER(ENTERTAINERNAME,ENTERTAINERPHONE,ENTERTAINERTYPE,ENTERTAINERID)
 VALUES('Beulah Figueroa',8114746454,'violin',ENTERTAINER_ENTERTAINERID_SEQ.nextval);
 
 INSERT INTO ENTERTAINER(ENTERTAINERNAME,ENTERTAINERPHONE,ENTERTAINERTYPE,ENTERTAINERID)
 VALUES('Clifton Malone',8334557235,'cello',ENTERTAINER_ENTERTAINERID_SEQ.nextval);
 
 INSERT INTO ENTERTAINER(ENTERTAINERNAME,ENTERTAINERPHONE,ENTERTAINERTYPE,ENTERTAINERID)
 VALUES('Alyssa Baker',8554631312,'guitar',ENTERTAINER_ENTERTAINERID_SEQ.nextval);
 
 INSERT INTO ENTERTAINER(ENTERTAINERNAME,ENTERTAINERPHONE,ENTERTAINERTYPE,ENTERTAINERID)
 VALUES('Susie Mcguire',8550700709,'tango',ENTERTAINER_ENTERTAINERID_SEQ.nextval);
 
 INSERT INTO ENTERTAINER(ENTERTAINERNAME,ENTERTAINERPHONE,ENTERTAINERTYPE,ENTERTAINERID)
 VALUES('Kate Buchanan',8558382838,'opera',ENTERTAINER_ENTERTAINERID_SEQ.nextval);
 
 INSERT INTO ENTERTAINER(ENTERTAINERNAME,ENTERTAINERPHONE,ENTERTAINERTYPE,ENTERTAINERID)
 VALUES('Alan Rivera',8558301753,'jazz',ENTERTAINER_ENTERTAINERID_SEQ.nextval);
 
 INSERT INTO ENTERTAINER(ENTERTAINERNAME,ENTERTAINERPHONE,ENTERTAINERTYPE,ENTERTAINERID)
 VALUES('Fannie Walters',8552736858,'flamenco',ENTERTAINER_ENTERTAINERID_SEQ.nextval);
 
 INSERT INTO ENTERTAINER(ENTERTAINERNAME,ENTERTAINERPHONE,ENTERTAINERTYPE,ENTERTAINERID)
 VALUES('Joyce Berry',8112890982,'solo dance',ENTERTAINER_ENTERTAINERID_SEQ.nextval);
 
 INSERT INTO ENTERTAINER(ENTERTAINERNAME,ENTERTAINERPHONE,ENTERTAINERTYPE,ENTERTAINERID)
 VALUES('Claude George',8112011494,'morden dance',ENTERTAINER_ENTERTAINERID_SEQ.nextval);
 
  INSERT INTO ENTERTAINER(ENTERTAINERNAME,ENTERTAINERPHONE,ENTERTAINERTYPE,ENTERTAINERID)
 VALUES('Sara Boone',8443450082,'cello',ENTERTAINER_ENTERTAINERID_SEQ.nextval);
 
  INSERT INTO ENTERTAINER(ENTERTAINERNAME,ENTERTAINERPHONE,ENTERTAINERTYPE,ENTERTAINERID)
 VALUES('Curtis Clark',8410550161,'violin',ENTERTAINER_ENTERTAINERID_SEQ.nextval);

--insert data --music-----
---drop sequence&create sequence---
drop sequence "TANG_YAO_IND_PROJ"."MUSIC_MUSICID_SEQ";
CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."MUSIC_MUSICID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
----truncate data permenately --
truncate table music;
INSERT INTO music (MUSICCONTACT, MUSICCONTACTPHONE, MUSICTYPE, MUSICID) VALUES ('Jake Cornish', 2025540122, 'pop', MUSIC_MUSICID_SEQ.NEXTVAL);
INSERT INTO music (MUSICCONTACT, MUSICCONTACTPHONE, MUSICTYPE, MUSICID) VALUES ('Nathan Parsons', 2025540137, 'falk', MUSIC_MUSICID_SEQ.NEXTVAL);
INSERT INTO music (MUSICCONTACT, MUSICCONTACTPHONE, MUSICTYPE, MUSICID) VALUES ('William Campbell', 2025540183, 'rock ', MUSIC_MUSICID_SEQ.NEXTVAL);
INSERT INTO music (MUSICCONTACT, MUSICCONTACTPHONE, MUSICTYPE, MUSICID) VALUES ('Brian Hardacre', 2025540160, 'country', MUSIC_MUSICID_SEQ.NEXTVAL);
INSERT INTO music (MUSICCONTACT, MUSICCONTACTPHONE, MUSICTYPE, MUSICID) VALUES ('Ava Lawrence', 2025540130, 'electronic', MUSIC_MUSICID_SEQ.NEXTVAL);
INSERT INTO music (MUSICCONTACT, MUSICCONTACTPHONE, MUSICTYPE, MUSICID) VALUES ('Owen Harris', 2025540105, 'blues', MUSIC_MUSICID_SEQ.NEXTVAL);
INSERT INTO music (MUSICCONTACT, MUSICCONTACTPHONE, MUSICTYPE, MUSICID) VALUES ('Wanda Ogden', 2025540123, 'soul', MUSIC_MUSICID_SEQ.NEXTVAL);
INSERT INTO music (MUSICCONTACT, MUSICCONTACTPHONE, MUSICTYPE, MUSICID) VALUES ('Lily McGrath', 2025540181, 'alternative', MUSIC_MUSICID_SEQ.NEXTVAL);
INSERT INTO music (MUSICCONTACT, MUSICCONTACTPHONE, MUSICTYPE, MUSICID) VALUES ('Vanessa Lawrence', 2025540182, 'pop', MUSIC_MUSICID_SEQ.NEXTVAL);
INSERT INTO music (MUSICCONTACT, MUSICCONTACTPHONE, MUSICTYPE, MUSICID) VALUES ('Jake McLean', 2025540167, 'falk', MUSIC_MUSICID_SEQ.NEXTVAL);
INSERT INTO music (MUSICCONTACT, MUSICCONTACTPHONE, MUSICTYPE, MUSICID) VALUES ('Dylan Hodges', 2025540162, 'rock ', MUSIC_MUSICID_SEQ.NEXTVAL);
INSERT INTO music (MUSICCONTACT, MUSICCONTACTPHONE, MUSICTYPE, MUSICID) VALUES ('Angela Sanderson', 2025540174, 'country', MUSIC_MUSICID_SEQ.NEXTVAL);
INSERT INTO music (MUSICCONTACT, MUSICCONTACTPHONE, MUSICTYPE, MUSICID) VALUES ('Jason Skinner', 2025530186, 'electronic', MUSIC_MUSICID_SEQ.NEXTVAL);
INSERT INTO music (MUSICCONTACT, MUSICCONTACTPHONE, MUSICTYPE, MUSICID) VALUES ('Austin Reid', 2025540173, 'blues', MUSIC_MUSICID_SEQ.NEXTVAL);
INSERT INTO music (MUSICCONTACT, MUSICCONTACTPHONE, MUSICTYPE, MUSICID) VALUES ('Edward Sutherland', 2025540106, 'soul', MUSIC_MUSICID_SEQ.NEXTVAL);

---insert data--photographer--
DROP SEQUENCE "TANG_YAO_IND_PROJ"."PHOTOGRAPHER_PHOTOGRAPHERID_S";
CREATE SEQUENCE"TANG_YAO_IND_PROJ"."PHOTOGRAPHER_PHOTOGRAPHERID_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
TRUNCATE TABLE PHOTOGRAPHER;

INSERT INTO photographer (PHOTOGRAPHERNAME, PHOTOGRAPHERPHONE, PHOTOGRAPHERID) VALUES ('Kristi Douglas', 2025550182, PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL);
INSERT INTO photographer (PHOTOGRAPHERNAME, PHOTOGRAPHERPHONE, PHOTOGRAPHERID) VALUES ('Zachary Guzman', 2025550152, PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL);
INSERT INTO photographer (PHOTOGRAPHERNAME, PHOTOGRAPHERPHONE, PHOTOGRAPHERID) VALUES ('Marlene Norton', 2025550155, PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL);
INSERT INTO photographer (PHOTOGRAPHERNAME, PHOTOGRAPHERPHONE, PHOTOGRAPHERID) VALUES ('Rex Sanders', 2025550190, PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL);
INSERT INTO photographer (PHOTOGRAPHERNAME, PHOTOGRAPHERPHONE, PHOTOGRAPHERID) VALUES ('Dolores Quinn', 2025550131, PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL);
INSERT INTO photographer (PHOTOGRAPHERNAME, PHOTOGRAPHERPHONE, PHOTOGRAPHERID) VALUES ('Bridget Sutton', 2025550174, PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL);
INSERT INTO photographer (PHOTOGRAPHERNAME, PHOTOGRAPHERPHONE, PHOTOGRAPHERID) VALUES ('Silvia Perkins', 2025550135, PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL);
INSERT INTO photographer (PHOTOGRAPHERNAME, PHOTOGRAPHERPHONE, PHOTOGRAPHERID) VALUES ('Kathy Wood', 2025550195, PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL);
INSERT INTO photographer (PHOTOGRAPHERNAME, PHOTOGRAPHERPHONE, PHOTOGRAPHERID) VALUES ('Donna Lambert', 2025550130, PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL);
INSERT INTO photographer (PHOTOGRAPHERNAME, PHOTOGRAPHERPHONE, PHOTOGRAPHERID) VALUES ('Clayton Howard', 2025550110, PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL);
INSERT INTO photographer (PHOTOGRAPHERNAME, PHOTOGRAPHERPHONE, PHOTOGRAPHERID) VALUES ('Sonia Bush', 2025550163, PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL);
INSERT INTO photographer (PHOTOGRAPHERNAME, PHOTOGRAPHERPHONE, PHOTOGRAPHERID) VALUES ('Sheldon Palmer', 2025550158, PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL);
INSERT INTO photographer (PHOTOGRAPHERNAME, PHOTOGRAPHERPHONE, PHOTOGRAPHERID) VALUES ('Margie Butler', 2025550107, PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL);
INSERT INTO photographer (PHOTOGRAPHERNAME, PHOTOGRAPHERPHONE, PHOTOGRAPHERID) VALUES ('Rene Harvey', 2025555174, PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL);
INSERT INTO photographer (PHOTOGRAPHERNAME, PHOTOGRAPHERPHONE, PHOTOGRAPHERID) VALUES ('Edwin Nelson', 2025550104, PHOTOGRAPHER_PHOTOGRAPHERID_S.NEXTVAL);


 --insert data location--
 drop sequence  "TANG_YAO_IND_PROJ"."LOCATION_LOCATIONID_SEQ";
 CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."LOCATION_LOCATIONID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--
truncate table location;

 INSERT INTO LOCATION(LOCATIONNAME,LOCATIONSTREET,ZIPID,LOCATIONID)
 VALUES('Quakertowncenter','20 Ivy Court',16,LOCATION_LOCATIONID_SEQ.nextval);
 
 INSERT INTO LOCATION(LOCATIONNAME,LOCATIONSTREET,ZIPID,LOCATIONID)
 VALUES('Montgomerycenter','661 Cherry Street',17,LOCATION_LOCATIONID_SEQ.nextval);
 
 INSERT INTO LOCATION(LOCATIONNAME,LOCATIONSTREET,ZIPID,LOCATIONID)
 VALUES('Cheshirecenter','116 Belmont Avenue',18,LOCATION_LOCATIONID_SEQ.nextval);
 
 INSERT INTO LOCATION(LOCATIONNAME,LOCATIONSTREET,ZIPID,LOCATIONID)
 VALUES('Rapidcenter','123 Route 29',19,LOCATION_LOCATIONID_SEQ.nextval);
 
 INSERT INTO LOCATION(LOCATIONNAME,LOCATIONSTREET,ZIPID,LOCATIONID)
 VALUES('Dearborncenter','840 Route 9',20,LOCATION_LOCATIONID_SEQ.nextval);
 
 INSERT INTO LOCATION(LOCATIONNAME,LOCATIONSTREET,ZIPID,LOCATIONID)
 VALUES('Pearlcenter','420 Smith Street',21,LOCATION_LOCATIONID_SEQ.nextval);
 
  INSERT INTO LOCATION(LOCATIONNAME,LOCATIONSTREET,ZIPID,LOCATIONID)
 VALUES('Michigancenter','33 Grant Avenue',22,LOCATION_LOCATIONID_SEQ.nextval);
 
  INSERT INTO LOCATION(LOCATIONNAME,LOCATIONSTREET,ZIPID,LOCATIONID)
 VALUES('Williamsportcenter','313 Country Lane',23,LOCATION_LOCATIONID_SEQ.nextval);
 
  INSERT INTO LOCATION(LOCATIONNAME,LOCATIONSTREET,ZIPID,LOCATIONID)
 VALUES('Villa Ricacenter','155 13th Street',24,LOCATION_LOCATIONID_SEQ.nextval);
 
  INSERT INTO LOCATION(LOCATIONNAME,LOCATIONSTREET,ZIPID,LOCATIONID)
 VALUES('Perkasiecenter','36 Bay Street',25,LOCATION_LOCATIONID_SEQ.nextval);
 
  INSERT INTO LOCATION(LOCATIONNAME,LOCATIONSTREET,ZIPID,LOCATIONID)
 VALUES('Great Fallscenter','85 Elmwood Avenue',26,LOCATION_LOCATIONID_SEQ.nextval);
 
  INSERT INTO LOCATION(LOCATIONNAME,LOCATIONSTREET,ZIPID,LOCATIONID)
 VALUES('Baycenter','238 Deerfield Drive',27,LOCATION_LOCATIONID_SEQ.nextval);
 
  INSERT INTO LOCATION(LOCATIONNAME,LOCATIONSTREET,ZIPID,LOCATIONID)
 VALUES('Charlottesvillecenter','780 Surrey Lane',28,LOCATION_LOCATIONID_SEQ.nextval);
 
  INSERT INTO LOCATION(LOCATIONNAME,LOCATIONSTREET,ZIPID,LOCATIONID)
 VALUES('Rosellecenter','272 4th Avenue',29,LOCATION_LOCATIONID_SEQ.nextval);
 
  INSERT INTO LOCATION(LOCATIONNAME,LOCATIONSTREET,ZIPID,LOCATIONID)
 VALUES('Mentorcenter','355 Central Avenue ',30,LOCATION_LOCATIONID_SEQ.nextval);
 
 ---insert data for florist--
 drop sequence "TANG_YAO_IND_PROJ"."FLORIST_FLORISTID_SEQ";
CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."FLORIST_FLORISTID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--
 truncate table florist;
 
 INSERT INTO FLORIST(FLORISTNAME,FLORISTPHONE,FLORISTID)
 VALUES('Sunshine Florist',3025540122,FLORIST_FLORISTID_SEQ.nextval);
 
 INSERT INTO FLORIST(FLORISTNAME,FLORISTPHONE,FLORISTID)
 VALUES('Roses are Red',3025540137,FLORIST_FLORISTID_SEQ.nextval);
 
 INSERT INTO FLORIST(FLORISTNAME,FLORISTPHONE,FLORISTID)
 VALUES('The Watering Can',3025540183,FLORIST_FLORISTID_SEQ.nextval);
 
 INSERT INTO FLORIST(FLORISTNAME,FLORISTPHONE,FLORISTID)
 VALUES('The Tilted Tulip',3025540160,FLORIST_FLORISTID_SEQ.nextval);
 
 INSERT INTO FLORIST(FLORISTNAME,FLORISTPHONE,FLORISTID)
 VALUES('Fabulous Flowers',3025540130,FLORIST_FLORISTID_SEQ.nextval);
 
 INSERT INTO FLORIST(FLORISTNAME,FLORISTPHONE,FLORISTID)
 VALUES('Smell the Roses',3025540105,FLORIST_FLORISTID_SEQ.nextval);

 INSERT INTO FLORIST(FLORISTNAME,FLORISTPHONE,FLORISTID)
 VALUES('Over the Moon Florist',3025540123,FLORIST_FLORISTID_SEQ.nextval);
 
 INSERT INTO FLORIST(FLORISTNAME,FLORISTPHONE,FLORISTID)
 VALUES('Buncha Flowers',3025540181,FLORIST_FLORISTID_SEQ.nextval);
 
  INSERT INTO FLORIST(FLORISTNAME,FLORISTPHONE,FLORISTID)
 VALUES('Happy Stems Florist',3025540186,FLORIST_FLORISTID_SEQ.nextval);
 
  INSERT INTO FLORIST(FLORISTNAME,FLORISTPHONE,FLORISTID)
 VALUES('Crazy Daisys Flowers',3025540167,FLORIST_FLORISTID_SEQ.nextval);
 
  INSERT INTO FLORIST(FLORISTNAME,FLORISTPHONE,FLORISTID)
 VALUES('Bonzai Florist',3025540162,FLORIST_FLORISTID_SEQ.nextval);
 
  INSERT INTO FLORIST(FLORISTNAME,FLORISTPHONE,FLORISTID)
 VALUES('The Secret Garden',3025540174,FLORIST_FLORISTID_SEQ.nextval);
 
  INSERT INTO FLORIST(FLORISTNAME,FLORISTPHONE,FLORISTID)
 VALUES('Infinity Flowers',3024540186,FLORIST_FLORISTID_SEQ.nextval);
 
 INSERT INTO FLORIST(FLORISTNAME,FLORISTPHONE,FLORISTID)
 VALUES('She Loves Me Flowers',3025540173,FLORIST_FLORISTID_SEQ.nextval);
 
  INSERT INTO FLORIST(FLORISTNAME,FLORISTPHONE,FLORISTID)
 VALUES('Busy Bee Florist',3025540106,FLORIST_FLORISTID_SEQ.nextval);
 
 ---insert data --client---
drop sequence "TANG_YAO_IND_PROJ"."CLIENT_CLIENTID_SEQ";
 CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."CLIENT_CLIENTID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
---
 truncate table client;
 
---client

insert into client (clientid, clname, cfname, cphone, cstreet, zipid) values(CLIENT_CLIENTID_SEQ.NEXTVAL, 'Brycen','Levy','8559475261','338 Hickory Street',1);
INSERT INTO client (clientid	,clname,cfname,	cphone,cstreet,zipid) VALUES(CLIENT_CLIENTID_SEQ.NEXTVAL,'Leilani','Friedman',8222808371,'191 Olive Street ',2);

INSERT INTO client (clientid	,clname,cfname,	cphone,cstreet,zipid) VALUES(CLIENT_CLIENTID_SEQ.NEXTVAL,'Leo','Ward',8229111661,'942 James Street ',3);

INSERT INTO  client (clientid	,clname,cfname,	cphone,cstreet,zipid) VALUES(CLIENT_CLIENTID_SEQ.NEXTVAL,'Justice','Johnston', 8999858991 ,'962 Route 5 ',4);

INSERT INTO  client(clientid	,clname,cfname,	cphone,cstreet,zipid) VALUES(CLIENT_CLIENTID_SEQ.NEXTVAL,'Madyson','Yu', 8114746451 ,'439 Clark Street',5);

INSERT INTO  client(clientid	,clname,cfname,	cphone,cstreet,zipid) VALUES(CLIENT_CLIENTID_SEQ.NEXTVAL,'Paul','Kemp', 8334557231 ,'696 Wall Street',6);

INSERT INTO client (clientid	,clname,cfname,	cphone,cstreet,zipid) VALUES(CLIENT_CLIENTID_SEQ.NEXTVAL,'Johnny','Faulkner', 8554631311,'806 John Street',7);

INSERT INTO client (clientid	,clname,cfname,	cphone,cstreet,zipid) VALUES(CLIENT_CLIENTID_SEQ.NEXTVAL,'Evelin','Douglas', 8550700701,'166 Railroad Avenue ',8);

INSERT INTO  client(clientid	,clname,cfname,	cphone,cstreet,zipid) VALUES(CLIENT_CLIENTID_SEQ.NEXTVAL,'Braiden','Mayer', 8558382831,'934 King Street',9);

INSERT INTO  client(clientid	,clname,cfname,	cphone,cstreet,zipid) VALUES(CLIENT_CLIENTID_SEQ.NEXTVAL,'Essence','Zavala', 8558301751,'588 Buttonwood Drive',10);

INSERT INTO  client(clientid	,clname,cfname,	cphone,cstreet,zipid) VALUES(CLIENT_CLIENTID_SEQ.NEXTVAL,'Lennon','Phelps', 8552736851,'26 7th Street',11);

INSERT INTO  client(clientid	,clname,cfname,	cphone,cstreet,zipid) VALUES(CLIENT_CLIENTID_SEQ.NEXTVAL,'Crystal','Higgins', 8112890981,'828 Prospect Avenue',12);

INSERT INTO  client(clientid	,clname,cfname,	cphone,cstreet,zipid) VALUES(CLIENT_CLIENTID_SEQ.NEXTVAL,'Michelle','Ponce', 8112011491,'625 Spruce Avenue',13);

INSERT INTO  client(clientid	,clname,cfname,	cphone,cstreet,zipid) VALUES(CLIENT_CLIENTID_SEQ.NEXTVAL,'Marcus','Hays', 8443450081,'100 Route 5',14);

INSERT INTO  client(clientid	,clname,cfname,	cphone,cstreet,zipid) VALUES(CLIENT_CLIENTID_SEQ.NEXTVAL,'Jordan','Wright', 8410550160,'81 Somerset Drive',15);
 
 
 DROP SEQUENCE"TANG_YAO_IND_PROJ"."MENU_MENUID_SEQ";
CREATE SEQUENCE"TANG_YAO_IND_PROJ"."MENU_MENUID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
TRUNCATE TABLE MENU; 
 
 
 
 
 INSERT INTO MENU(MENUNUMBER,MENUID,MENUAPPETIZER,MENUSALAD,MENUMAIN,MENUDESSERT)
 VALUES(100,MENU_MENUID_SEQ.nextval,'Goat Cheese Trio','Farmers Salad ','Spicy Fried Chicken','Jeferson Donut');
 
 INSERT INTO MENU(MENUNUMBER,MENUID,MENUAPPETIZER,MENUSALAD,MENUMAIN,MENUDESSERT)
 VALUES(101,MENU_MENUID_SEQ.nextval,'Cannellini Bruschetta','Farro Arugula','green beansBeer Can Chicken','Diplomat Cake');
 
 INSERT INTO MENU(MENUNUMBER,MENUID,MENUAPPETIZER,MENUSALAD,MENUMAIN,MENUDESSERT)
 VALUES(102,MENU_MENUID_SEQ.nextval,'Spiced Olives','Spinach Bacon Blue','Chicken Pot Pie','Coconut Banana Creme Pie');
 
 INSERT INTO MENU(MENUNUMBER,MENUID,MENUAPPETIZER,MENUSALAD,MENUMAIN,MENUDESSERT)
 VALUES(103,MENU_MENUID_SEQ.nextval,'Radish-Anchovy Canapes','Many Vegetable','Chicken & Spinach Enchilada','JPeanut Butter');
 
 INSERT INTO MENU(MENUNUMBER,MENUID,MENUAPPETIZER,MENUSALAD,MENUMAIN,MENUDESSERT)
 VALUES(104,MENU_MENUID_SEQ.nextval,'Blue Cheese–Pecan Spread','Spicy Ahi Tuna Poke','Fried Chicken','Blue Ribbon Apple Pie');
 
 INSERT INTO MENU(MENUNUMBER,MENUID,MENUAPPETIZER,MENUSALAD,MENUMAIN,MENUDESSERT)
 VALUES(105,MENU_MENUID_SEQ.nextval,'Kale-Artichoke Dip','Bleu Cheese Steak','Southern Fried Chicken','Ednas Carrot Cake');
 
 INSERT INTO MENU(MENUNUMBER,MENUID,MENUAPPETIZER,MENUSALAD,MENUMAIN,MENUDESSERT)
 VALUES(106,MENU_MENUID_SEQ.nextval,'Indian Yogurt Dip','Chicken Salad Salad','Spicy Fried Chicken','Tuxedo Cake');
 
 INSERT INTO MENU(MENUNUMBER,MENUID,MENUAPPETIZER,MENUSALAD,MENUMAIN,MENUDESSERT)
 VALUES(107,MENU_MENUID_SEQ.nextval,'Goat Cheese Trio','Ceviche & Greens','green beansBeer Can Chicken','Shortbrd Cookie');
 
 INSERT INTO MENU(MENUNUMBER,MENUID,MENUAPPETIZER,MENUSALAD,MENUMAIN,MENUDESSERT)
 VALUES(108,MENU_MENUID_SEQ.nextval,'Cannellini Bruschetta','Farmers Salad','Chicken Pot Pie','Macaroon Cookie');
 
 INSERT INTO MENU(MENUNUMBER,MENUID,MENUAPPETIZER,MENUSALAD,MENUMAIN,MENUDESSERT)
 VALUES(109,MENU_MENUID_SEQ.nextval,'Spiced Olives','Farro Arugula','Chicken & Spinach Enchilada','Choc Chip Cookie');
 
 INSERT INTO MENU(MENUNUMBER,MENUID,MENUAPPETIZER,MENUSALAD,MENUMAIN,MENUDESSERT)
 VALUES(110,MENU_MENUID_SEQ.nextval,'Radish-Anchovy Canapes','Spinach Bacon Blue','Fried Chicken','PB Cookie');
 
 INSERT INTO MENU(MENUNUMBER,MENUID,MENUAPPETIZER,MENUSALAD,MENUMAIN,MENUDESSERT)
 VALUES(111,MENU_MENUID_SEQ.nextval,'Blue Cheese–Pecan Spread','Many Vegetable','Southern Fried Chicken','Snickerdoodle Cookie');
 
 INSERT INTO MENU(MENUNUMBER,MENUID,MENUAPPETIZER,MENUSALAD,MENUMAIN,MENUDESSERT)
 VALUES(112,MENU_MENUID_SEQ.nextval,'Kale-Artichoke Dip','Spicy Ahi Tuna Poke','SSpicy Fried Chicken','Fresh apples thick cut');
 
 INSERT INTO MENU(MENUNUMBER,MENUID,MENUAPPETIZER,MENUSALAD,MENUMAIN,MENUDESSERT)
 VALUES(113,MENU_MENUID_SEQ.nextval,'Indian Yogurt Dip','Bleu Cheese Steak','green beansBeer Can Chicken','flaky pastry dough');
 
 INSERT INTO MENU(MENUNUMBER,MENUID,MENUAPPETIZER,MENUSALAD,MENUMAIN,MENUDESSERT)
 VALUES(114,MENU_MENUID_SEQ.nextval,'Goat Cheese Trio','Chicken Salad Salad','Chicken Pot Pie','vanilla ice crea');
 
 ---insert event---
 --
 ----insert data for event
-------------
drop sequence "TANG_YAO_IND_PROJ"."EVENT_EVENTID_SEQ";
CREATE SEQUENCE  "TANG_YAO_IND_PROJ"."EVENT_EVENTID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
---
truncate table event;
insert into event(eventID,CLIENTID,EVENTDATE,EVENTSTARTTIME,EVENTDURATION,EVENTTYPE,NUMBERGUESTS,LOCATIONID,LINENCOLORREQUESTED,NUMBERWAITERS,NUMBERBARTENDERS,floristid,floristcost,musicid,musiccost,photographerid,photographercost,menuid,entertainercost,entertainerid,totalprice) values(event_eventid_seq.nextval,5,to_date('08-Jun-15'),13,5,'wedding',177,1,7,17,5,5,200,5,746.5,6,48,1,155,6,150);
insert into event(eventID,CLIENTID,EVENTDATE,EVENTSTARTTIME,EVENTDURATION,EVENTTYPE,NUMBERGUESTS,LOCATIONID,LINENCOLORREQUESTED,NUMBERWAITERS,NUMBERBARTENDERS,floristid,floristcost,musicid,musiccost,photographerid,photographercost,menuid,entertainercost,entertainerid,totalprice) values(event_eventid_seq.nextval,9,to_date('03-Aug-15'),14,6,'wedding',150,5,6,20,7,6,300,5,50.5,7,60,8,344,6,200);
insert into event(eventID,CLIENTID,EVENTDATE,EVENTSTARTTIME,EVENTDURATION,EVENTTYPE,NUMBERGUESTS,LOCATIONID,LINENCOLORREQUESTED,NUMBERWAITERS,NUMBERBARTENDERS,floristid,floristcost,musicid,musiccost,photographerid,photographercost,menuid,entertainercost,entertainerid,totalprice) values(event_eventid_seq.nextval,6,to_date('05-Aug-15'),14,3,'food festival',150,2,8,50,8,7,100.5,6,34.5,5,65,7,665,8,100);
insert into event(eventID,CLIENTID,EVENTDATE,EVENTSTARTTIME,EVENTDURATION,EVENTTYPE,NUMBERGUESTS,LOCATIONID,LINENCOLORREQUESTED,NUMBERWAITERS,NUMBERBARTENDERS,floristid,floristcost,musicid,musiccost,photographerid,photographercost,menuid,entertainercost,entertainerid,totalprice) values(event_eventid_seq.nextval,8,to_date('06-Aug-15'),14,4,'culture festival',140,8,9,40,7,8,120.5,7,35,8,69,10,144,4,200);
insert into event(eventID,CLIENTID,EVENTDATE,EVENTSTARTTIME,EVENTDURATION,EVENTTYPE,NUMBERGUESTS,LOCATIONID,LINENCOLORREQUESTED,NUMBERWAITERS,NUMBERBARTENDERS,floristid,floristcost,musicid,musiccost,photographerid,photographercost,menuid,entertainercost,entertainerid,totalprice) values(event_eventid_seq.nextval,7,to_date('02-Sep-15'),14,5,'competition',50,5,10,40,8,9,125.5,8,46,10,90,1,140,1,100);
insert into event(eventID,CLIENTID,EVENTDATE,EVENTSTARTTIME,EVENTDURATION,EVENTTYPE,NUMBERGUESTS,LOCATIONID,LINENCOLORREQUESTED,NUMBERWAITERS,NUMBERBARTENDERS,floristid,floristcost,musicid,musiccost,photographerid,photographercost,menuid,entertainercost,entertainerid,totalprice) values(event_eventid_seq.nextval,5,to_date('08-Jun-15'),13,5,'wedding',177,1,7,17,5,5,200,5,746.5,6,48,1,155,6,150);
insert into event(eventID,CLIENTID,EVENTDATE,EVENTSTARTTIME,EVENTDURATION,EVENTTYPE,NUMBERGUESTS,LOCATIONID,LINENCOLORREQUESTED,NUMBERWAITERS,NUMBERBARTENDERS,floristid,floristcost,musicid,musiccost,photographerid,photographercost,menuid,entertainercost,entertainerid,totalprice) values(event_eventid_seq.nextval,9,to_date('03-Aug-15'),14,6,'wedding',150,5,6,20,7,6,300,5,50.5,7,60,8,344,6,200);
insert into event(eventID,CLIENTID,EVENTDATE,EVENTSTARTTIME,EVENTDURATION,EVENTTYPE,NUMBERGUESTS,LOCATIONID,LINENCOLORREQUESTED,NUMBERWAITERS,NUMBERBARTENDERS,floristid,floristcost,musicid,musiccost,photographerid,photographercost,menuid,entertainercost,entertainerid,totalprice) values(event_eventid_seq.nextval,6,to_date('05-Aug-15'),14,3,'food festival',150,2,8,50,8,7,100.5,6,34.5,5,65,7,665,8,100);
insert into event(eventID,CLIENTID,EVENTDATE,EVENTSTARTTIME,EVENTDURATION,EVENTTYPE,NUMBERGUESTS,LOCATIONID,LINENCOLORREQUESTED,NUMBERWAITERS,NUMBERBARTENDERS,floristid,floristcost,musicid,musiccost,photographerid,photographercost,menuid,entertainercost,entertainerid,totalprice) values(event_eventid_seq.nextval,8,to_date('06-Aug-15'),14,4,'culture festival',140,8,9,40,7,8,120.5,7,35,8,69,10,144,4,200);
insert into event(eventID,CLIENTID,EVENTDATE,EVENTSTARTTIME,EVENTDURATION,EVENTTYPE,NUMBERGUESTS,LOCATIONID,LINENCOLORREQUESTED,NUMBERWAITERS,NUMBERBARTENDERS,floristid,floristcost,musicid,musiccost,photographerid,photographercost,menuid,entertainercost,entertainerid,totalprice) values(event_eventid_seq.nextval,7,to_date('02-Sep-15'),14,5,'competition',50,5,10,40,8,9,125.5,8,46,10,90,1,140,1,100);
insert into event(eventID,CLIENTID,EVENTDATE,EVENTSTARTTIME,EVENTDURATION,EVENTTYPE,NUMBERGUESTS,LOCATIONID,LINENCOLORREQUESTED,NUMBERWAITERS,NUMBERBARTENDERS,floristid,floristcost,musicid,musiccost,photographerid,photographercost,menuid,entertainercost,entertainerid,totalprice) values(event_eventid_seq.nextval,8,to_date('22-Oct-15'),14,6,'culture festival',166,1,11,20,6,10,130,9,50,9,100,13,166,10,130);
insert into event(eventID,CLIENTID,EVENTDATE,EVENTSTARTTIME,EVENTDURATION,EVENTTYPE,NUMBERGUESTS,LOCATIONID,LINENCOLORREQUESTED,NUMBERWAITERS,NUMBERBARTENDERS,floristid,floristcost,musicid,musiccost,photographerid,photographercost,menuid,entertainercost,entertainerid,totalprice) values(event_eventid_seq.nextval,9,to_date('03-Nov-15'),15,7,'funeral',40,7,13,20,9,11,135,1,150,10,65,14,177,12,150);
insert into event(eventID,CLIENTID,EVENTDATE,EVENTSTARTTIME,EVENTDURATION,EVENTTYPE,NUMBERGUESTS,LOCATIONID,LINENCOLORREQUESTED,NUMBERWAITERS,NUMBERBARTENDERS,floristid,floristcost,musicid,musiccost,photographerid,photographercost,menuid,entertainercost,entertainerid,totalprice) values(event_eventid_seq.nextval,13,to_date('06-Nov-15'),15,4,'wedding',150,10,14,16,8,13,140,2,230,13,80,15,188,4,300);
insert into event(eventID,CLIENTID,EVENTDATE,EVENTSTARTTIME,EVENTDURATION,EVENTTYPE,NUMBERGUESTS,LOCATIONID,LINENCOLORREQUESTED,NUMBERWAITERS,NUMBERBARTENDERS,floristid,floristcost,musicid,musiccost,photographerid,photographercost,menuid,entertainercost,entertainerid,totalprice) values(event_eventid_seq.nextval,2,to_date('23-Nov-15'),15,5,'competition',70,13,15,6,5,4,145.5,3,40,14,140,8,199,8,160);
insert into event(eventID,CLIENTID,EVENTDATE,EVENTSTARTTIME,EVENTDURATION,EVENTTYPE,NUMBERGUESTS,LOCATIONID,LINENCOLORREQUESTED,NUMBERWAITERS,NUMBERBARTENDERS,floristid,floristcost,musicid,musiccost,photographerid,photographercost,menuid,entertainercost,entertainerid,totalprice) values(event_eventid_seq.nextval,4,to_date('02-Dec-15'),16,6,'competition',80,15,2,5,9,15,155,4,350,15,100,8,200,9,180);
